---
title: "Rwaves"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Rwaves}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Rwaves)
```

# Read data in

In order to read the data in use the ANA format.

```{r read}
f <- system.file("extdata", package = "Rwaves")
x <- readData(f, estention = "ANA")
```

# Data analysis

In order to obtain results do:

```{r analysis}
y <- rwaves(x)
y

        # total number of "X"
    ff89 <- function(x){
        newname <- paste0("f89_5")
        out <- x %>%
    dplyr::mutate(index1 = dplyr::case_when(waveforms == 5 ~ 1,
                              waveforms == 2 ~ 0,
                              TRUE ~ 3)) %>%
    dplyr::mutate(index1 = ifelse(index1 == 3, NA, index1)) %>%
    tidyr::fill(index1) %>%
    dplyr::mutate(index2 = ifelse(index1 == 1 & dplyr::lead(index1 == 0), 1, 0)) %>%
    dplyr::summarise(Sum = sum(index2, na.rm = TRUE)) %>%
    dplyr::rename(!!newname := Sum)
       if(nrow(out) == 0){
           out[1, 1] <- 0
       }
       return(out)
    }


    # total duration of "X"
    ff90 <- function(x){
        newname <- paste0("f90_5")
        x$cum <- c(diff(x$time), x$time[length(x$time)])
        out <- x %>%
    dplyr::mutate(index1 = dplyr::case_when(waveforms == 5 ~ 1,
                              waveforms == 2 ~ 0,
                              TRUE ~ 3)) %>%
    dplyr::mutate(index1 = ifelse(index1 == 3, NA, index1)) %>%
    tidyr::fill(index1) %>%
    dplyr::mutate(index2 = ifelse(index1 == 1 & dplyr::lead(index1 == 0), 1, 0)) %>%
    dplyr::filter(index1 == 1) %>%
    dplyr::summarise(Sum = sum(cum, na.rm = TRUE)) %>%
    dplyr::rename(!!newname := Sum)
       if(nrow(out) == 0){
           out[1, 1] <- 0
       }
       return(out)
    }



y <- x %>%
    dplyr::mutate(pippo = dplyr::row_number()) %>%
    dplyr::mutate(index1 = dplyr::case_when(waveforms == 5 ~ 1,
                              waveforms == 2 ~ 0,
                              TRUE ~ 3)) %>%
    dplyr::mutate(index1 = ifelse(index1 == 3, NA, index1)) %>%
    tidyr::fill(index1) %>%
    dplyr::mutate(index2 = ifelse(index1 == 1 & dplyr::lead(index1 == 0), 1, 0))


y %>%
    summarise(sum(index2, na.rm = TRUE))

       dplyr::filter(waveforms == d) %>%
       dplyr::group_by(waveforms) %>%
       dplyr::summarize(Sum = sum(cum)) %>%
       dplyr::select(Sum) %>%
       dplyr::rename(!!newname := Sum)
   if(nrow(out) == 0){
       out[1, 1] <- 0
   }
   return(out)
}


```
